# Indexação e fatiamento (slicing)

In [1]:
# Importando o NumPy
import numpy as np

In [3]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([2, 6, 0, 2, 2, 0, 6, 4, 2, 9])

In [4]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[18, 41, 15, 32, 98],
       [35, 81, 23, 15, 46],
       [18, 21, 92, 65,  7],
       [45, 87, 53, 36, 29]])

In [5]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.95047576, 0.28387569, 0.39018077, 0.4101434 , 0.84686563],
        [0.45122203, 0.80512133, 0.67918218, 0.51564587, 0.88124379],
        [0.08960898, 0.744089  , 0.22619875, 0.17423402, 0.12338124],
        [0.11953402, 0.63693833, 0.04137103, 0.42996416, 0.61299739]],

       [[0.0921162 , 0.36138885, 0.45056398, 0.15212834, 0.69614462],
        [0.78390733, 0.33855031, 0.91017118, 0.92758773, 0.07672989],
        [0.60454425, 0.26955637, 0.47235992, 0.31431681, 0.75981562],
        [0.72164709, 0.16480818, 0.54658344, 0.00765507, 0.73118411]],

       [[0.45758144, 0.2292944 , 0.50914657, 0.32424433, 0.01065189],
        [0.20258677, 0.47475028, 0.99352697, 0.90426054, 0.9515727 ],
        [0.29888807, 0.24350312, 0.62148088, 0.45508145, 0.21818154],
        [0.09666926, 0.52792481, 0.24010734, 0.1643924 , 0.14832783]]])

### Acessando elementos específicos

In [6]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([2, 6, 0, 2, 2, 0, 6, 4, 2, 9])

In [7]:
# nome_do_array[índice]
a1D[0]

2

In [8]:
a1D[2]

0

In [9]:
a1D[-1]

9

In [10]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([2, 2, 9])

In [11]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[18, 41, 15, 32, 98],
       [35, 81, 23, 15, 46],
       [18, 21, 92, 65,  7],
       [45, 87, 53, 36, 29]])

In [12]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

23

In [13]:
a2D[3][4]

29

In [14]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([18, 81, 92, 36])

In [15]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([32, 23, 21, 45])

In [16]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([36, 92, 81, 18])

In [17]:
a2D[:,[0,1,2,0]] 

array([[18, 41, 15, 18],
       [35, 81, 23, 35],
       [18, 21, 92, 18],
       [45, 87, 53, 45]])

In [18]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[35, 81, 23, 35],
       [18, 41, 15, 18],
       [35, 81, 23, 35],
       [18, 41, 15, 18]])

In [19]:
a2D

array([[18, 41, 15, 32, 98],
       [35, 81, 23, 15, 46],
       [18, 21, 92, 65,  7],
       [45, 87, 53, 36, 29]])

In [20]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[35, 81, 23, 35],
       [18, 41, 15, 18],
       [35, 81, 23, 35],
       [18, 41, 15, 18]])

In [21]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.95047576, 0.28387569, 0.39018077, 0.4101434 , 0.84686563],
        [0.45122203, 0.80512133, 0.67918218, 0.51564587, 0.88124379],
        [0.08960898, 0.744089  , 0.22619875, 0.17423402, 0.12338124],
        [0.11953402, 0.63693833, 0.04137103, 0.42996416, 0.61299739]],

       [[0.0921162 , 0.36138885, 0.45056398, 0.15212834, 0.69614462],
        [0.78390733, 0.33855031, 0.91017118, 0.92758773, 0.07672989],
        [0.60454425, 0.26955637, 0.47235992, 0.31431681, 0.75981562],
        [0.72164709, 0.16480818, 0.54658344, 0.00765507, 0.73118411]],

       [[0.45758144, 0.2292944 , 0.50914657, 0.32424433, 0.01065189],
        [0.20258677, 0.47475028, 0.99352697, 0.90426054, 0.9515727 ],
        [0.29888807, 0.24350312, 0.62148088, 0.45508145, 0.21818154],
        [0.09666926, 0.52792481, 0.24010734, 0.1643924 , 0.14832783]]])

In [22]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.32424433245953077

In [23]:
a3D[0][3][1]

0.6369383304185015

### Fatiamento (slicing)

In [24]:
# Array de 1 dimensão
a1D

array([2, 6, 0, 2, 2, 0, 6, 4, 2, 9])

In [25]:
a = a1D[1:5] # Índice 1 ao 4
a

array([6, 0, 2, 2])

In [26]:
b = a1D[0:6] # Índice 0 ao 5
b

array([2, 6, 0, 2, 2, 0])

In [27]:
c = a1D[:6] # Do início ao 5
c

array([2, 6, 0, 2, 2, 0])

In [28]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([2, 0, 2, 6, 2])

In [29]:
e = a1D[-1::-1] # Do final até o início
e

array([9, 2, 4, 6, 0, 2, 2, 0, 6, 2])

In [30]:
# Array de 2 dimensões
a2D

array([[18, 41, 15, 32, 98],
       [35, 81, 23, 15, 46],
       [18, 21, 92, 65,  7],
       [45, 87, 53, 36, 29]])

In [31]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([18, 41, 15, 32, 98])

In [32]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

array([35, 81, 23, 15, 46])

In [33]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([21, 92, 65])

In [34]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

array([45, 87, 53, 36, 29])

In [35]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([15, 23, 92, 53])

In [36]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([15, 65, 36])

In [37]:
# Array de 3 dimensões
a3D

array([[[0.95047576, 0.28387569, 0.39018077, 0.4101434 , 0.84686563],
        [0.45122203, 0.80512133, 0.67918218, 0.51564587, 0.88124379],
        [0.08960898, 0.744089  , 0.22619875, 0.17423402, 0.12338124],
        [0.11953402, 0.63693833, 0.04137103, 0.42996416, 0.61299739]],

       [[0.0921162 , 0.36138885, 0.45056398, 0.15212834, 0.69614462],
        [0.78390733, 0.33855031, 0.91017118, 0.92758773, 0.07672989],
        [0.60454425, 0.26955637, 0.47235992, 0.31431681, 0.75981562],
        [0.72164709, 0.16480818, 0.54658344, 0.00765507, 0.73118411]],

       [[0.45758144, 0.2292944 , 0.50914657, 0.32424433, 0.01065189],
        [0.20258677, 0.47475028, 0.99352697, 0.90426054, 0.9515727 ],
        [0.29888807, 0.24350312, 0.62148088, 0.45508145, 0.21818154],
        [0.09666926, 0.52792481, 0.24010734, 0.1643924 , 0.14832783]]])

In [38]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.0921162 , 0.36138885, 0.45056398, 0.15212834, 0.69614462],
       [0.78390733, 0.33855031, 0.91017118, 0.92758773, 0.07672989],
       [0.60454425, 0.26955637, 0.47235992, 0.31431681, 0.75981562],
       [0.72164709, 0.16480818, 0.54658344, 0.00765507, 0.73118411]])

In [39]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.36138885, 0.45056398, 0.15212834],
       [0.33855031, 0.91017118, 0.92758773],
       [0.26955637, 0.47235992, 0.31431681]])

In [40]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.08960898, 0.744089  , 0.22619875, 0.17423402, 0.12338124])

In [41]:
a3D

array([[[0.95047576, 0.28387569, 0.39018077, 0.4101434 , 0.84686563],
        [0.45122203, 0.80512133, 0.67918218, 0.51564587, 0.88124379],
        [0.08960898, 0.744089  , 0.22619875, 0.17423402, 0.12338124],
        [0.11953402, 0.63693833, 0.04137103, 0.42996416, 0.61299739]],

       [[0.0921162 , 0.36138885, 0.45056398, 0.15212834, 0.69614462],
        [0.78390733, 0.33855031, 0.91017118, 0.92758773, 0.07672989],
        [0.60454425, 0.26955637, 0.47235992, 0.31431681, 0.75981562],
        [0.72164709, 0.16480818, 0.54658344, 0.00765507, 0.73118411]],

       [[0.45758144, 0.2292944 , 0.50914657, 0.32424433, 0.01065189],
        [0.20258677, 0.47475028, 0.99352697, 0.90426054, 0.9515727 ],
        [0.29888807, 0.24350312, 0.62148088, 0.45508145, 0.21818154],
        [0.09666926, 0.52792481, 0.24010734, 0.1643924 , 0.14832783]]])

In [42]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.45122203, 0.80512133, 0.67918218, 0.51564587, 0.88124379],
       [0.78390733, 0.33855031, 0.91017118, 0.92758773, 0.07672989],
       [0.20258677, 0.47475028, 0.99352697, 0.90426054, 0.9515727 ]])

In [43]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.4101434 , 0.51564587, 0.17423402, 0.42996416],
       [0.15212834, 0.92758773, 0.31431681, 0.00765507],
       [0.32424433, 0.90426054, 0.45508145, 0.1643924 ]])

### Indexação com booleanos

In [44]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[325,  81, 464, 222, 101,  88, 221, 409],
       [468, 311, 147, 354, 442, 216, 186, 220],
       [200, 101, 449, 360,  21, 239, 182, 203],
       [355, 314, 120,  28, 473, 294,  65, 113],
       [155, 462,  84, 215,  85, 335, 446,  48],
       [ 81,  78, 369, 327, 478, 157, 362, 123],
       [222, 182, 484, 195, 277,  56, 138, 252],
       [485, 426, 450,   1, 105, 257, 287, 383],
       [ 54, 457,  41, 434, 270, 407, 496, 315],
       [296, 425,  21, 258, 201, 406, 235, 214]])

In [45]:
a2D >= 250

array([[ True, False,  True, False, False, False, False,  True],
       [ True,  True, False,  True,  True, False, False, False],
       [False, False,  True,  True, False, False, False, False],
       [ True,  True, False, False,  True,  True, False, False],
       [False,  True, False, False, False,  True,  True, False],
       [False, False,  True,  True,  True, False,  True, False],
       [False, False,  True, False,  True, False, False,  True],
       [ True,  True,  True, False, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True,  True,  True],
       [ True,  True, False,  True, False,  True, False, False]])

In [46]:
a2D[a2D >= 250]

array([325, 464, 409, 468, 311, 354, 442, 449, 360, 355, 314, 473, 294,
       462, 335, 446, 369, 327, 478, 362, 484, 277, 252, 485, 426, 450,
       257, 287, 383, 457, 434, 270, 407, 496, 315, 296, 425, 258, 406])

In [47]:
a2D.mean()

253.8375

In [48]:
a2D[a2D <= a2D.mean()]

array([ 81, 222, 101,  88, 221, 147, 216, 186, 220, 200, 101,  21, 239,
       182, 203, 120,  28,  65, 113, 155,  84, 215,  85,  48,  81,  78,
       157, 123, 222, 182, 195,  56, 138, 252,   1, 105,  54,  41,  21,
       201, 235, 214])