# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([3, 7, 8, 6, 9, 8, 9, 7, 9, 8])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[93, 12, 12, 80, 26],
       [40, 21, 44, 58, 36],
       [43, 43,  9, 79,  6],
       [77, 90, 53, 46, 67]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.30348176, 0.98142009, 0.71817379, 0.83685506, 0.21356787],
        [0.77142511, 0.03878921, 0.09789708, 0.89001403, 0.41481411],
        [0.87311308, 0.96408254, 0.85233038, 0.49335386, 0.1631343 ],
        [0.56408437, 0.81972021, 0.75007799, 0.8020197 , 0.75611363]],

       [[0.80669122, 0.6516963 , 0.57314003, 0.60360334, 0.48929651],
        [0.40621133, 0.07247921, 0.95763597, 0.00686834, 0.39641762],
        [0.45453947, 0.72503463, 0.58906533, 0.3810005 , 0.64988115],
        [0.5007773 , 0.19394858, 0.20941992, 0.91728042, 0.11030289]],

       [[0.80903631, 0.48376964, 0.31408913, 0.70088683, 0.8417018 ],
        [0.20212102, 0.38473678, 0.60903853, 0.02229587, 0.19018475],
        [0.29146582, 0.20615854, 0.87749945, 0.47819039, 0.60746547],
        [0.64601713, 0.93238577, 0.94148713, 0.29453712, 0.02565494]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [6]:
a2D.shape

(4, 5)

In [7]:
a3D.shape

(3, 4, 5)

In [8]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [9]:
a2D.ndim

2

In [10]:
a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [11]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [12]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [13]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [14]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [15]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [16]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [17]:
a1D.size

10

In [18]:
a2D.size

20

In [19]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [20]:
a1D.dtype

dtype('int32')

In [21]:
a1D.dtype.name

'int32'

In [22]:
a2D.dtype

dtype('int32')

In [23]:
a2D.dtype.name

'int32'

In [24]:
a3D.dtype

dtype('float64')

In [25]:
a3D.dtype.name

'float64'