In [1]:
import numpy as np

In [2]:
series = [[23,45,12,679], [14,48,69,38]]
new_series = np.array(series)
print(new_series.ndim)
print(new_series.shape)

2
(2, 4)


In [11]:
a = np.full(10,4)

In [12]:
a

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [13]:
import numpy as np

percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype.name)

float64


In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[arr%2==0]=-1

In [16]:
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [25]:
arr = np.eye(5)

In [26]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr = arr - (np.eye(5) + 1)

In [29]:
arr

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [35]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[-2::-2] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])